---
- name: Ensure Portainer stack is deployed
  docker_stack:
    state: present
    name: portainer
    compose:
      src: "{{ role_path }}/templates/portainer.yaml.j2"
    prune: yes
    resolve_image: always
