all:
  hosts:
    manager1:
      ansible_host: 192.0.2.1
    manager2:
      ansible_host: 198.51.100.1
    manager3:
      ansible_host: 203.0.113.1
    worker1:
      ansible_host: 192.0.2.2
    worker2:
      ansible_host: 198.51.100.2
    worker3:
      ansible_host: 203.0.113.2
    worker-db:
      ansible_host: 192.0.2.3
  children:
    managers:
      hosts:
        manager1:
        manager2:
        manager3:
    db_node:
      hosts:
        worker-db:
    app_nodes:
      hosts:
        worker1:
        worker2:
        worker3:
